---
title: "Trust in Authoritarian Regimes"
author: 
output: html_document
runtime: shiny
---

CHECK ESTIMATES

We know a lot about the relationship between basic demographic and socio-economic variables and political outcomes, such as political participation and trust in the government, in the United States and other developed democracies. However, we know a lot less about predictors of political beliefs in authoritarian regimes. 
In exploring 

I created this app using data from the latest round of the [World Values Survey](http://www.worldvaluessurvey.org/WVSDocumentationWV6.jsp), which was conducted in more than 50 countries between 2011 and 2014. I include the 21 countries with non-democratic governments. I plot the predicted probability that someone will trust the government by age and by level of education. The solid lines represent the averages, and the colored ribbons around the lines represent the 95% confidence intervals (see below for discussion of other control variables used).

In many countries, there are not significant differences in how much people trust the government across education levels. 
In others, like Kuwait, China, and Morrocco, 

[Description]
Kuwait, China, Morrocco

Singapore - China is higher
Nigeria - all the same

### Education, Age, and Trust in the State
```{r, echo=FALSE, warning=FALSE, message=FALSE}
trust <- function() {
library(shiny)
library(ggplot2)
library(devtools)
shinyApp(
        ui = fluidPage(fluidRow(
                        column(8,
                                selectInput("countryyr", label = "Choose a country:", 
                                c("Algeria - 2014" = 1, "Azerbaijan - 2011/2012" = 2, 
                                "Armenia - 2011" = 3,  "Belarus - 2011" = 3, "China - 2012" = 4, 
                                "Palestine - 2013" = 5, "Iraq - 2013" = 6, "Kazakhstan - 2011" = 7, 
                                "Jordan - 2014"= 8, "Kuwait - 2013" = 9, "Libya - 2013" = 10, 
                                "Malaysia - 2011" = 11, "Morocco - 2011" = 12, "Nigeria - 2011" = 13,
                                "Qatar - 2010" = 14, "Russia - 2011" = 15, "Rwanda - 2012" = 16, 
                                "Singapore - 2012" = 17, "Zimbabwe - 2011" = 18, "Egypt - 2012" = 19,
                                "Uzbekistan - 2011" = 20, "Yemen - 2013" = 21), selected = 1))),
                             
                mainPanel(
                        #uiOutput("ggvis_ui"),
                        plotOutput('plot')
                  )),

        server = (function(input, output) {
        #source_gist("4466237")
        
        data_predict <- read.csv("C:/Dropbox/Projects/Dissertation/WVS/trust.app/20141209_data_forapp.csv")
        output$plot <- renderPlot(function(){
                 selection <- input$countryyr      
#                 selection <- switch(input$countryyr,
#                                     "Algeria - 2014" = "Algeria - 2014", "Azerbaijan - 2011/2012" = "Azerbaijan - 2011/2012", "Armenia - 2011" = "Armenia - 2011",  "Belarus - 2011" = "Belarus - 2011", "China - 2012" = "China - 2012", "Palestine - 2013" = "Palestine - 2013", "Iraq - 2013" = "Iraq - 2013", "Kazakhstan - 2011" = "Kazakhstan - 2011", "Jordan - 2014" = "Jordan - 2014", "Kuwait - 2013" = "Kuwait - 2013", "Libya - 2013" = "Libya - 2013", "Malaysia - 2011" = "Malaysia - 2011", "Morocco - 2011" = "Morocco - 2011", "Nigeria - 2011" = "Nigeria - 2011", "Qatar - 2010" = "Qatar - 2010", "Russia - 2011" = "Russia - 2011", "Rwanda - 2012" = "Rwanda - 2012", "Singapore - 2012" = "Singapore - 2012", "Zimbabwe - 2011" = "Zimbabwe - 2011", "Egypt - 2012" = "Egypt - 2012", "Uzbekistan - 2011" = "Uzbekistan - 2011", "Yemen - 2013" = "Yemen - 2013")
#                 
                data <- subset(data_predict, cyr_n == input$countryyr) 
                data$category <- factor(data$category, levels = c("College", "High School", "< High School"))

                p <- ggplot(data, aes(x =age, y = predictedprob)) + 
                        theme_bw() +
                         theme(#axis.line = element_line(colour = "black"),
                                #plot.background = element_blank(),
#                               panel.grid.minor= element_blank(),
#                               panel.grid.major.x = element_blank(),
#                               panel.grid.major.y = element_blank(),
                              panel.border = element_blank(),
                              panel.background = element_blank()) +  
                        geom_ribbon(aes(ymin = LL, ymax = UL, fill = category), alpha = 0.2) + 
                        geom_line(aes(color = category), size = 1.2) +
                        xlab("Age") + ylab("Probability of Trust")
                print(p)
                
        })
        
            
}))

}

trust()
```


### Data and Model
I model trust in the state using logistic regression, with a separate model for each country. To measure trust, I use the question "How much confidence do you have in the government (in your nation's capital)? A great deal, quite a lot, not very much, or none at all?" The former two are counted as trusting the state, while the latter two are counted as not trusting.

In addition to age and level of education, I use the following regressors: income (measured in declines by country), gender, unemployment status, and political interest. The plots are for an employed female with average income. The level of political interest is set at 0 (not interested in politics) or 1 (interested in politics), depending on whether the country's average is above 0.5. Go [here](https://github.com/jchaskell/trust.app/blob/master/create.app.Rmd) for the R Markdown file that creates the app and go [here](https://github.com/jchaskell/trust.app/blob/master/create.data.R) for the (though it doesn't start from the raw data).

Note: this is meant as a preliminary model - more of a first pass of the data. Instead of printing out twenty one graphs, I decided to use the opportunity to learn how to create a `shiny` app. 



